Import('env')
Import('iotivity_resource_inc_paths')

oic_libs = ['oc', 'octbstack', 'oc_logger', 'rcs_container', 'rcs_client', 'rcs_server', 'rcs_common']

env_samples = env.Clone()
env_samples['CPPPATH'] = iotivity_resource_inc_paths
env_samples.AppendUnique(CPPPATH = ['#/include/'])
env_samples['LIBS'] = [oic_libs, 'pthread']
env_samples['LIBPATH'] = ['${IOTIVITY_BASE}/out/linux/${TARGET_ARCH}/${IOTIVITY_LIB_TYPE}']

iotApp_cpp = ['AVTransport.cpp',
              'iotApp.cpp',
              'BinarySwitch.cpp',
              'Brightness.cpp',
              'Light.cpp',
              'CommandlineMode.cpp',
              'ContentDirectory.cpp',
              'ConnectionManager.cpp',
              'InteractiveMode.cpp',
              'IotivityUtility.cpp',
              'MenuBase.cpp',
              'MenuBinarySwitch.cpp',
              'MenuBrightness.cpp',
              'MenuConnectionManager.cpp',
              'MenuContentDirectory.cpp',
              'MenuDevices.cpp',
              'MenuIotivity.cpp',
              'MenuLight.cpp',
              'MenuMain.cpp',
              'MenuServices.cpp']
iotApp_obj = env_samples.Object(iotApp_cpp)
iotApp_bins = env_samples.Program('iotApp', iotApp_obj)

env.Install('#/${BUILD_DIR}/bin', iotApp_bins)