#******************************************************************
#
# Copyright 2016 Intel Corporation All Rights Reserved.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Import('env')
Import('iotivity_resource_inc_paths')

oic_libs = ['oc', 'octbstack', 'oc_logger', 'rcs_container', 'rcs_client', 'rcs_server', 'rcs_common']

env_bridge = env.Clone()
env_bridge.AppendUnique(LIBS = oic_libs)
examples_bins = env_bridge.Program('UpnpBridge.cpp')

env_samples = env.Clone()
env_samples['CPPPATH'] = iotivity_resource_inc_paths
env_samples.AppendUnique(CPPPATH = ['#/include/'])
env_samples['LIBS'] = [oic_libs, 'pthread']
env_samples['LIBPATH'] = ['${IOTIVITY_BASE}/out/linux/${TARGET_ARCH}/${IOTIVITY_LIB_TYPE}']
examples_bins.extend(env_samples.Program('Client.cpp'))
examples_bins.extend(env_samples.Program('SimpleClient.cpp'))
examples_bins.extend(env_samples.Program('Observer.cpp'))

env.Install('#/${BUILD_DIR}/bin', examples_bins)
env.Install('#/${BUILD_DIR}/bin', 'BundleConfig.xml')
