#******************************************************************
#
# Copyright 2016 Intel Corporation All Rights Reserved.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Import('env')

upnp_iotivity_bridge_cpp = ['UpnpManager.cpp',
                            'UpnpResource.cpp',
                            'UpnpException.cpp',
                            'UpnpDevice.cpp',
                            'UpnpService.cpp',
                            'UpnpAttribute.cpp',
                            'UpnpConnector.cpp',
                            'UpnpBundleActivator.cpp',
                            'UpnpConnectionManagerService.cpp',
                            'UpnpAVTransportService.cpp',
                            'UpnpContentDirectoryService.cpp',
                            'UpnpRenderingControlService.cpp',
                            'UpnpScheduledRecordingService.cpp',
                            'UpnpDimmingService.cpp',
                            'UpnpPowerSwitchService.cpp',
                            'UpnpWanCommonInterfaceConfigService.cpp']
#upnp_iotivity_bridge_obj = env.SharedObject(upnp_iotivity_bridge_cpp)
upnpbundle_lib = env.SharedLibrary('UpnpBundle', upnp_iotivity_bridge_cpp)

Return('upnpbundle_lib')
